services:
  - type: web
    name: fncs-api
    runtime: python
    pythonVersion: "3.11.0"
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --config gunicorn_config.py app:app
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: JWT_ALGORITHM
        value: HS256
      - key: JWT_ACCESS_TOKEN_EXPIRES
        value: "3600"
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: "False"
